### PR TITLE
fix: default twitter og preview to use `summary_large_image` for bigger previews

### LINKED ISSUE #3104: Use large preview by default in social cards
By default twitter renders a card like this 
image

But we want it like this: 
image

Meta needed to be set by default:

twitter:card content: summary_large_image

### PR DESCRIPTION
**Pull request by JayaKrishnaNamburu**
## Description

fixes #3104 

For forcing twitter to use large-card size. We need to set `summary_large_image` meta tag in the header.

## Steps for reproduction

- Create a new project with a page.
- Set an image for the social image in the page settings.
- Deploy the site, and check the open graph preview using some of the tools online

https://tweethunter.io/tweetpik/twitter-card-validator?url=https%3A%2F%2Fcelebrated-pony-026734.netlify.app%2F
Screenshot 2025-05-06 at 8 41 02 PM

https://robolly.com/twitter-card-preview?url=https://celebrated-pony-026734.netlify.app

Screenshot 2025-05-06 at 8 40 57 PM

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [x] made a self-review

## Before merging

- [x] tested locally and on preview environment (preview dev login: 0000)
- [x] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document

### CODE REVIEW

File: packages/react-sdk/src/page-settings-meta.tsx [hunk 1]
```diff
@@ -137,5 +137,12 @@ export const PageSettingsMeta = ({
 
   metas.push(...pageMeta.custom);
 
+  const isTwitterCardSizeExists = pageMeta.custom.some(
```
Comment (kof) [inline packages/react-sdk/src/page-settings-meta.tsx:140]: so this will only work if twitter:card meta is added? why not always have it if there is og image provided?

Comment (JayaKrishnaNamburu) [reply packages/react-sdk/src/page-settings-meta.tsx]: It's jst a check to see if users added `twitter:card` and skips if there is any. Or else, adds the `summary_large_image`. Just to give preference to whatever it is added. Renamed it for better red-ability.

**Review by kof — APPROVED** [review]
didn't test

**Comment by kof** [comment]
Please create a branch with .staging in the end of the name like this https://github.com/webstudio-is/webstudio/pull/5167 and it will allow publishing from staging so we can test

**Comment by JayaKrishnaNamburu** [comment]
> #5167

Got it, will create one 👍

**Comment by JayaKrishnaNamburu** [comment]
@kof pushed a new branch with the `.staging` at the end. You can test the deployments here
https://twitter-card.staging.webstudio.is/dashboard

**Comment by kof** [comment]
Works perfectly!

**Review by kof — APPROVED** [review]
