### PR TITLE
fix: AI Command Bar improvements

### LINKED ISSUE #2473: AI Command Bar improvements 10/13
- [x] Add placeholder text: Welcome to Webstudio AI alpha
- [x] Remove the shortcut temporarily since we haven't decided on one.
- [x] Add new middle paragraph to Welcome message and new button: "Share feedback" (@kof where should this go? Where do you want to receive feedback?)
Screenshot 2023-10-13 at 11 26 19 AM

- [x] Change the variant of the "Cancel" button from neutral to dark-ghost for a better appearance. Design is updated in figma.
Screenshot 2023-10-13 at 12 13 21 PM

- [x] Please show the enabled AI button while placeholder text is visible. This helps the AI feature look more interesting and discoverable. The button still won’t do anything without a prompt and will still be disabled when voice recording/transcribing or in the error state.
- [x] Please place the scroll bar centered in the margins of the menu rather than overlapping the buttons.
Screenshot 2023-10-13 at 11 35 37 AM

- [x] Display previous prompts with the newest at the top. Currently the oldest is at the top of the list.
- [x] Add a tooltip to previous prompts (not instant; normal delay)
Screenshot 2023-10-13 at 12 24 08 PM

Figma: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=7500-40455&mode=design

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #2473

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/builder/features/ai/ai-command-bar.tsx [hunk 1]
```diff
@@ -439,15 +485,28 @@ const CommandBarContent = (props: {
...
+              }}
+            >
+              <Grid gap={2} css={{ margin: 4, marginRight: 14 }}>
                 {props.prompts.map((prompt, index) => (
-                  <CommandBarContentPrompt
+                  <Tooltip
                     key={index}
-                    onClick={() => props.onPromptClick(prompt)}
+                    side="top"
+                    // sideOffset={10}
```
Comment (TrySound) [inline apps/builder/app/builder/features/ai/ai-command-bar.tsx:500]: Remove comment?

**Review by TrySound — APPROVED** [review]
