### PR TITLE
fix: Canvas crash with Failed to execute 'matches' on 'Element': ':current' is not a valid selector.

### LINKED ISSUE #4622: Canvas crash with Failed to execute 'matches' on 'Element': ':current' is not a valid selector.
Here is the error we got Failed to execute 'matches' on 'Element': ':current' is not a valid selector.

image

Repro https://discord.com/channels/@me/1137111913810108426/1319279052434968697

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #4622

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 0000)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

### CODE REVIEW

File: apps/builder/app/canvas/instance-selected.ts [hunk 1]
```diff
@@ -233,8 +234,12 @@ const subscribeSelectedInstance = (
     }
     const activeStates = new Set<string>();
     for (const state of availableStates) {
-      if (element.matches(state)) {
-        activeStates.add(state);
+      try {
```
Comment (TrySound) [inline apps/builder/app/canvas/instance-selected.ts:237]: could you please add comment some pseudo classes like :open or :current are not supported in .matches method

**Review by TrySound — APPROVED** [review]
