### PR TITLE
fix: Prevent focus when selecting form label in builder

### LINKED ISSUE #4513: Prevent focus when selecting form label in builder
When selecting a form label that as the `for` property, the field is focused preventing editing the label via the canvas.

We should prevent the default behavior here when within a building mode.

1. Add form label and input
2. Give label a `for` value that matches the input's `id`
3. Try selecting label in builder to edit

https://github.com/user-attachments/assets/c9babc59-b19a-49aa-a697-ec91bbaba71c

### PR DESCRIPTION
**Pull request by istarkov**
## Description

Prevent forwarding the click event on an input element when the associated label has a "for" attribute

In real browser emulates click event on input when label is clicked.

closes #4513

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 0000)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

### CODE REVIEW

File: apps/builder/app/canvas/interceptor.ts [hunk 1]
```diff
@@ -70,6 +70,15 @@ const switchPageAndUpdateSystem = (href: string, formData?: FormData) => {
 
 export const subscribeInterceptedEvents = () => {
   const handleClick = (event: MouseEvent) => {
+    // Prevent forwarding the click event on an input element when the associated label has a "for" attribute
+    if (event.target instanceof Element) {
+      if (event.target.closest("label[for]")) {
+        if (!$isPreviewMode.get()) {
```
Comment (kof) [inline apps/builder/app/canvas/interceptor.ts:76]: do this first before you call other things

**Review by kof — APPROVED** [review]

File: apps/builder/app/canvas/interceptor.ts (hunk 1 above)
Comment (kof) [reply apps/builder/app/canvas/interceptor.ts:76]: also why is this a nested if instead of a single condition :)

**Review by TrySound — APPROVED** [review]
