### PR TITLE
fix(numeric-gesture-control): abstract PointerLock API

### LINKED ISSUE #99: NumericInput doesn't work in Safari
Currently, the `pointerLock` API which is used in the NumericInput causes Safari to show a special banner

https://user-images.githubusercontent.com/11071/176870343-9077ca47-7a47-487e-b5c7-3e337ae28eb3.mp4

I think we should not use this API since it's not clear how it's going to behave in different browsers. Also [from the docs](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) I read it's for games etc. which isn't our use case IMO.

### PR DESCRIPTION
**Pull request by ghost**
This abstracts the Pointer Lock browser API used in numeric gesture control, enhancing the experience of it on browsers that make it easy, along the same lines as what Figma does.

Fixes #99, more details on the issue.

### CODE REVIEW

File: app/shared/design-system/components/primitives/numeric-gesture-control.ts [hunk 1]
```diff
@@ -28,6 +28,14 @@ type Options = {
   }) => void;
 };
 
+type State = {
+  value: number;
+  cursor: SVGElement | null;
```
Comment (kof) [inline app/shared/design-system/components/primitives/numeric-gesture-control.ts:33]: Nit: I generally prefer undefined when possible, because it works with optional arguments in js

File: app/shared/design-system/components/primitives/numeric-gesture-control.ts [hunk 2]
```diff
@@ -108,25 +98,72 @@ export const numericGestureControl = (
...
+          <path d="M 15 4.5L 15 2L 11.5 5.5L 15 9L 15 6.5L 31 6.5L 31 9L 34.5 5.5L 31 2L 31 4.5Z" fill="#111" fill-rule="evenodd"></path>
+        </g>
+      </svg>`).firstElementChild as SVGElement;
+    cursorNode.style.position = "absolute";
+    cursorNode.style.left = `${event.offsetX}px`;
+    cursorNode.style.top = `${event.offsetY}px`;
+    cursorNode.style.transform =
+      state.direction === "horizontal" ? "rotate(0deg)" : "rotate(90deg)";
+    cursorNode.style.setProperty(
+      "--drop-shadow",
```
Comment (kof) [inline app/shared/design-system/components/primitives/numeric-gesture-control.ts:138]: why do you use a css var here vs setting it directly?

File: app/shared/design-system/components/primitives/numeric-gesture-control.ts [hunk 3]
```diff
@@ -108,25 +98,72 @@ export const numericGestureControl = (
...
+      `drop-shadow(${
+        state.direction === "horizontal" ? "0 1px" : "1px 0"
+      } 1.1px rgba(0,0,0,.4))`
+    );
+    state.cursor = cursorNode;
+    targetNode.ownerDocument.documentElement.append(state.cursor as Node);
```
Comment (kof) [inline app/shared/design-system/components/primitives/numeric-gesture-control.ts:144]: is `as` used because it cursor could be undefined/null? If yes then better way is to have an "if" check before you use the variable, because it can actually be unset potentially

File: app/shared/design-system/components/primitives/numeric-gesture-control.ts [hunk 4]
```diff
@@ -108,25 +98,72 @@ export const numericGestureControl = (
...
+    targetNode.onpointermove = () => {
+      (state.cursor as SVGElement).style[
```
Comment (kof) [inline app/shared/design-system/components/primitives/numeric-gesture-control.ts:146]: same here

File: app/shared/design-system/components/primitives/numeric-gesture-control.ts [hunk 5]
```diff
@@ -108,25 +98,72 @@ export const numericGestureControl = (
...
+
+const exitPointerLock = (
+  state: State,
+  event: PointerEvent,
+  targetNode: HTMLElement
+) => {
+  targetNode.releasePointerCapture(event.pointerId);
+
+  if (shouldUsePointerLock()) {
+    (state.cursor as SVGElement).remove();
```
Comment (kof) [inline app/shared/design-system/components/primitives/numeric-gesture-control.ts:161]: same here

File: app/shared/design-system/components/primitives/numeric-gesture-control.ts [hunk 6]
```diff
@@ -108,25 +98,72 @@ export const numericGestureControl = (
...
+    targetNode.onpointermove = null;
+    targetNode.ownerDocument.exitPointerLock();
+  }
+};
+
+const shouldUsePointerLock = () => {
```
Comment (kof) [inline app/shared/design-system/components/primitives/numeric-gesture-control.ts:167]: why is it a function, it could be just a value, right?

Comment (kof) [reply app/shared/design-system/components/primitives/numeric-gesture-control.ts:167]: when we are in node, this should be automatically fasle

File: app/shared/design-system/components/primitives/numeric-gesture-control.ts [hunk 7]
```diff
@@ -108,25 +98,72 @@ export const numericGestureControl = (
...
 
-const cursorNode = new Range().createContextualFragment(`
-  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="46" height="15" style="filter:var(--drop-shadow);">
-    <g transform="translate(2 3)">
-      <path d="M 15 4.5L 15 2L 11.5 5.5L 15 9L 15 6.5L 31 6.5L 31 9L 34.5 5.5L 31 2L 31 4.5Z" fill="#111" fill-rule="evenodd" stroke="#FFF" stroke-width="2"></path>
-      <path d="M 15 4.5L 15 2L 11.5 5.5L 15 9L 15 6.5L 31 6.5L 31 9L 34.5 5.5L 31 2L 31 4.5Z" fill="#111" fill-rule="evenodd"></path>
-    </g>
-  </svg>
-`).firstElementChild as HTMLElement;
+const requestPointerLock = (
```
Comment (kof) [inline app/shared/design-system/components/primitives/numeric-gesture-control.ts:116]: I think we need a good comment here how this works, nobody would understand it without context

**Review by kof — CHANGES_REQUESTED** [review]
first review done

File: app/shared/design-system/components/primitives/numeric-gesture-control.ts [hunk 8]
```diff
@@ -28,6 +28,14 @@ type Options = {
   }) => void;
 };
 
+type State = {
+  value: number;
+  cursor: SVGElement | undefined;
```
Comment (kof) [inline app/shared/design-system/components/primitives/numeric-gesture-control.ts:33]: same as
```suggestion
  cursor?: SVGElement;
```

**Review by kof — APPROVED** [review]
LGTM 🎉
