### PR TITLE
fix: Rate limit on shared link clicks

### LINKED ISSUE #4403: Rate limit shows as application error for share link projects
When clicking section links quickly, I get rate limited but it shows as an app error. Before it would show as an error with details.

**This project is shared with me via auth token.** The rate limit doesn't appear to be as sensitive for owned projects so idk if it's an issue for them.

https://github.com/user-attachments/assets/6bd227cd-6858-4b84-b8c4-67ced30a58a9

Site note, it's odd that requests are being made for same page links. Thought we fixed this.

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #4403

We have no way to show good errors on naviagation errors (remix does not support this)

Here I reduced amount of reloads on link clicks on preview

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 0000)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

### CODE REVIEW

File: apps/builder/app/shared/nano-states/props.ts [hunk 1]
```diff
@@ -718,6 +718,11 @@ export const subscribeResources = () => {
         cacheByKeys.set(cacheKey, undefined);
       }
 
+      const missingValues = Array.from(missing.values());
+      if (missingValues.length === 0) {
+        return;
+      }
```
Comment (TrySound) [inline apps/builder/app/shared/nano-states/props.ts:724]: does it invalidate resource when click "refresh" button?

Comment (istarkov) [reply apps/builder/app/shared/nano-states/props.ts:724]: From logic I see if missing is empty, nothing is loaded

**Review by TrySound — APPROVED** [review]
