### PR TITLE
fix: Prevent tooltip on focus

### LINKED ISSUE #4293: After using expression editor, canvas loses focus
After I use the expression editor, I can't scroll on the canvas until I click on it again.

1. Ensure the page has some room to scroll (eg 200vh)
2. Open expression editor
3. Click out of the expression editor, including clicking canvas directly
4. Try scrolling canvas
5. See no scroll 🙈 

https://github.com/user-attachments/assets/3a1ef1b6-cb5c-479c-9765-f9dd1777aed9

Borderline P2 bug. If too much effort maybe it's P2.

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #4293

One of solution also
```
        onCloseAutoFocus={(event) => {
          event.preventDefault();
        }}
```

on dialog and popover content, but it's lost element focus.

This solution doesn't lost focus. Just prevent tooltip from being shown on focus.

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

### CODE REVIEW

**Review by kof — APPROVED** [review]
please add a comment about WHY we decided to do that

File: packages/design-system/src/components/tooltip.tsx [hunk 1]
```diff
@@ -13,7 +13,7 @@ import { Box } from "./box";
 import { Text } from "./text";
 import type { CSS } from "../stitches.config";
 import { theme } from "../stitches.config";
-import { disableCanvasPointerEvents } from "../utilities";
+import { composeEventHandlers } from "@radix-ui/primitive";
```
Comment (TrySound) [inline packages/design-system/src/components/tooltip.tsx:16]: We already have such utility here
image

File: packages/design-system/src/components/tooltip.tsx [hunk 2]
```diff
@@ -78,18 +78,21 @@ export const Tooltip = forwardRef(
...
+     *    (This doesn't work well in Chrome, as scrolling stops working on elements hovered with pointer-events: none,
+     *    even after removing pointer-events.)
+     * 2. Close the tooltip on onMouseLeave.
+     *    (This breaks some grace area behavior, such as closing the tooltip when moving the mouse from the content to the trigger.)
+     *
+     * The simpler solution with fewer side effects is to close the tooltip on mouse leave.
+     */
+    const handleMouseEnterComposed = composeEventHandlers(() => {
+      setOpen(false);
+    }, props.onMouseLeave);
```
Comment (TrySound) [inline packages/design-system/src/components/tooltip.tsx:95]: Doesn't this do the same?
```
(event) => {
  setOpen(false);
  props.onMouseLeave?.(event)
}
```

Comment (istarkov) [reply packages/design-system/src/components/tooltip.tsx:95]: In current implementation yes. But what's wrong with using it.

Comment (TrySound) [reply packages/design-system/src/components/tooltip.tsx:95]: Extra direct dependency to maintain. Too little value

Comment (TrySound) [reply packages/design-system/src/components/tooltip.tsx:95]: And frankly I can only guess how it behaves. Explicit function call is just so much easier to read.

**Review by TrySound — APPROVED** [review]
