### PR TITLE
fix: Variable bindings on Class don't show on live site

### LINKED ISSUE #3683: Variable bindings on Class don't show on live site
1. Create string var like "Hi" (or a resource or any other var)
2. Bind the var to the Class Name field on any component such as heading
3. View in the builder dom it outputs
4. Publish and view in the live site it does NOT output

Notes:
- Works fine with IDs and custom attributes
- Works fine if I enter a static value
- Seems to only be an issue with classes + variables

https://github.com/webstudio-is/webstudio/assets/93934362/083609f4-fa89-4712-bc48-ac92c0318f4b

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #3683

## Steps for reproduction

Tests and fixtures

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

### CODE REVIEW

File: packages/react-sdk/src/component-generator.ts [hunk 1]
```diff
@@ -170,11 +170,17 @@ export const generateJsxElement = ({
   let collectionDataValue: undefined | string;
   let collectionItemValue: undefined | string;
 
-  const classes = Array.from(classesMap?.get(instance.id) ?? []);
+  const classMapArray = classesMap?.get(instance.id);
+  const classes =
+    classMapArray !== undefined
+      ? [JSON.stringify(classMapArray.join(" "))]
+      : [];
```
Comment (TrySound) [inline packages/react-sdk/src/component-generator.ts:177]: const classes = []
if (generatedClasses) {
  classes.push(JSON.stringify(generatedClasses.join(" ")))
}

**Review by TrySound — APPROVED** [review]
