### PR TITLE
fix: Dialog focus issues

### LINKED ISSUE #2889: Style panel updates unexpectedly when dialog content instance is selected
If you are selecting any instance that is inside of a Dialog content, then you will not be able to use on that instance display select or use keyboard arrows on numeric inputs, they will auto update

Same thing happens with sheet content

https://www.tella.tv/video/cls6xsfab00yg0fjy2h4e4spr/view

https://tella.video/arrow-keys-no-longer-working-on-some-inputs-scrub-inconsistency-issues-on-lower-end-hardware-3qht

https://www.tella.tv/video/cls6y71jo01at0gla4pzi3qht/

https://tella.video/alexs-video-4spr

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #2889

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/canvas/shared/styles.ts [hunk 1]
```diff
@@ -116,7 +116,43 @@ const subscribePreviewMode = () => {
 const subscribeEphemeralStyle = (params: Params) => {
   // track custom properties added on previous ephemeral styles change
   const addedCustomProperties = new Set<string>();
+
+  let timeoutHandle: number | undefined = undefined;
```
Comment (kof) [inline apps/builder/app/canvas/shared/styles.ts:120]: isn't this called timerId or timeoutId?

**Review by kof — APPROVED** [review]

File: apps/builder/app/canvas/shared/styles.ts (hunk 1 above)
Comment (istarkov) [reply apps/builder/app/canvas/shared/styles.ts:120]: handle in programming is an abstract reference to a resource that allows programmers to manage and interact with that resource 
All my life it was handle, have no idea why js named that timerId
