### PR TITLE
fix: Input arrow up and down pulls up autocomplete now instead of incrementing

### LINKED ISSUE #4287: Input arrow up and down pulls up autocomplete now instead of incrementing
When clicking into an input like width and trying to arrow up or down to increment, the autocomplete shows instead of incrementing.

https://github.com/user-attachments/assets/cfb3c223-81f5-4aa3-be2b-bd06fb62b1f7

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #4287

- [x] Up/Down now uses `onChange` instead of `onChangeComplete` (this should be faster)
- [x] Up/Down in the Space control now works with modifiers (it seems this never worked before)
- [x] Up/Down no longer opens the combobox if the input is numeric-like​⬤

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

### CODE REVIEW

**Review by johnsicili — APPROVED** [review]
You fixed spacing too!!! Good stuff long overdue :)

File: apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx [hunk 1]
```diff
@@ -692,9 +630,67 @@ export const CssValueInput = ({
...
+
+        onChangeComplete({ value: newValue, ...meta, type: "delta" });
+      } else {
+        props.onChange({
+          type: "unit",
+          value: handleNumericInputArrowKeys(inputValue, event),
+          unit: value.unit,
+        });
+      }
+      event.preventDefault();
```
Comment (kof) [inline apps/builder/app/builder/features/style-panel/shared/css-value-input/css-value-input.tsx:669]: its better to call this earler, so that others who get the event see event.defaultPrevented // true

**Review by kof — APPROVED** [review]
