### PR TITLE
fix: Fix focus bugs with text editing on canvas

### LINKED ISSUE #3021: Text Content does not propagate changes from Settings Panel if Previous Edit was on Canvas
image

Start Editing Text on Canvas then click to Settings/Text Content and proceed with editing. Text on canvas will not be updated until blur.

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #3021

Currently if we are in a text edit mode we sometimes can't focus on any input inside builder.
This fixes this.

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/shared/canvas-api.ts [hunk 1]
```diff
@@ -0,0 +1,71 @@
+import { setInert, resetInert } from "../canvas/shared/inert";
+
+const _canvasApi = {
```
Comment (kof) [inline apps/builder/app/shared/canvas-api.ts:3]: since this is on canvas where we will have 3rd party code running, I would use some namespace that looks like __webstudioSomething

File: apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar.tsx [hunk 2]
```diff
@@ -120,6 +120,10 @@ const Toolbar = ({ state, scale }: ToolbarProps) => {
       onClick={(event) => {
         event.stopPropagation();
       }}
+      onFocus={(event) => {
+        // We don't want the logic in the builder to make canvas inert to be triggered
+        event.preventDefault();
```
Comment (kof) [inline apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar.tsx:125]: is it not killing tabs and such?

File: apps/builder/app/builder/builder.tsx [hunk 3]
```diff
@@ -307,55 +309,91 @@ export const Builder = ({
...
+  const handleFocus = useCallback((event: React.FocusEvent) => {
+    // Ignore toolbar focus events. See the onFocus handler in text-toolbar.tsx
+    if (false === event.defaultPrevented) {
+      canvasApi.setInert();
+      $textEditingInstanceSelector.set(undefined);
+    }
+  }, []);
+
+  /**
+   * Prevent radix to steal focus during editing in the settings panel.
```
Comment (kof) [inline apps/builder/app/builder/builder.tsx:336]: will need a more detailed comment to 100% understand how to reproduce the situation, for the future self

Comment (istarkov) [reply apps/builder/app/builder/builder.tsx:336]: hover on setInert

File: apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar.tsx (hunk 2 above)
Comment (istarkov) [reply apps/builder/app/builder/features/workspace/canvas-tools/text-toolbar.tsx:125]: I never seen text toolbar was working with keyboard

File: apps/builder/app/builder/builder.tsx [hunk 4]
```diff
@@ -307,55 +309,98 @@ export const Builder = ({
...
+   * 5. Inert attribute is set asynchronously, but focus is already lost.
+   *
+   * Synchronous focusing and setInert prevent the text editor from focusing on render.
+   * This cannot be handled inside the canvas because the text editor toolbar is in the builder and focus events in the canvas should be ignored.
+   *
+   * Use onPointerDown instead of onFocus because Radix focus lock triggers on text edit blur
+   * before the focusin event when editing text inside a Radix dialog.
+   */
+  const handlePointerDown = useCallback(
+    (event: React.PointerEvent | React.FocusEvent) => {
```
Comment (TrySound) [inline apps/builder/app/builder/builder.tsx:331]: why focus event?

**Review by TrySound — APPROVED** [review]

File: apps/builder/app/builder/builder.tsx (hunk 4 above)
Comment (istarkov) [reply apps/builder/app/builder/builder.tsx:331]: Forgot to delete, thought both are needed but deleted onFocus

File: apps/builder/app/shared/canvas-api.ts [hunk 5]
```diff
@@ -0,0 +1,73 @@
+import { setInert, resetInert } from "../canvas/shared/inert";
+
+const apiWindowNamespace = "__webstudio__$__canvasApi";
+
+const _canvasApi = {
```
Comment (kof) [inline apps/builder/app/shared/canvas-api.ts:5]: if we have a nicely prefixed namespace, why do you need a _ before the name here?

File: apps/builder/app/shared/canvas-api.ts [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+  } catch (e) {
+    return true;
+  }
+};
+
+const getIframeApi = () => {
+  if (isInIframe()) {
+    // Inside the iframe, use the local window.api
+    return _canvasApi;
+  } else {
```
Comment (kof) [inline apps/builder/app/shared/canvas-api.ts:28]: after return else is not really needed, confuses me, though In know some people find it more readable

File: apps/builder/app/shared/canvas-api.ts [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+    // Find first iframe with the API
+    for (let i = 0; i < window.frames.length; ++i) {
```
Comment (kof) [inline apps/builder/app/shared/canvas-api.ts:30]: we aim to use full words, in this case "index"
