### PR TITLE
fix: Create a new page and mark it as home in the same step

### LINKED ISSUE #3470: Create a new page and mark it as home in the same step
When creating a page and marking it as home at the same step - it will fail to create a page

## Steps
1. create a page
2. check "make it home page"
3. hit create
4. nothing happens

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #3470

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx [hunk 1]
```diff
@@ -1505,11 +1504,22 @@ const updatePage = (pageId: Page["id"], values: Partial<Values>) => {
       return;
     }
 
+    if (pages.homePage.id === pageId) {
+      updatePageMutable(pages.homePage, values, pages.folders);
+    }
+
+    for (const page of pages.pages) {
```
Comment (kof) [inline apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx:1511]: seems like you would rather want to use .find or at least a break; once the page is found, .find is kinda making more semantical sense

**Review by kof — APPROVED** [review]

File: apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx (hunk 1 above)
Comment (istarkov) [reply apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx:1511]: I just moved that code lines, there are no new code, just order fix

Comment (kof) [reply apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx:1511]: iknow)

Comment (TrySound) [reply apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx]: honestly it's not better, for "semantics" we need .get(id)

Comment (kof) [reply apps/builder/app/builder/features/sidebar-left/panels/pages/page-settings.tsx]: .find() returns one element, its semantically clearly better, perf doesn't really matter here, since you won't have thouthands pages
