### PR TITLE
fix: Collection binding with JSON Variable not working

### LINKED ISSUE #3997: Collection binding with JSON Variable not working
When binding the JSON variable to Collection, nothing shows in the data field, and no children are present in the dom/navigator.

1. Create a JSON variable  (see below for sample)
2. Add a Collection
3. Bind the data property to it
4. See nothing show up in the data texarea. See no children of the Collection.

https://github.com/user-attachments/assets/7842e184-6a65-4370-9a28-47e4007a68ca

```JSON
{
  "name": "Test Object",
  "data": [
    {
      "id": 1,
      "values": [
        [
          1,
          2,
          3
        ],
        [
          4,
          5,
          6
        ]
      ]
    },
    {
      "id": 2,
      "values": [
        [
          7,
          8,
          9
        ],
        [
          10,
          11,
          12
        ]
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #3997

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

### CODE REVIEW

File: apps/builder/app/shared/nano-states/props.ts [hunk 1]
```diff
@@ -226,17 +226,53 @@ export const computeExpression = (
...
       ])
     );
 
     const result = new Function("_variables", code)(proxiedVariables);
     return result;
-  } catch {
+  } catch (e) {
     // empty block
+    console.error(e);
   }
```
Comment (kof) [inline apps/builder/app/shared/nano-states/props.ts:276]:
```suggestion
  } catch (error) {
    console.error(error);
  }
```

**Review by kof — APPROVED** [review]

**Review by johnsicili — APPROVED** [review]
Thank you!! Looks good

**Review by TrySound — APPROVED** [review]
